name: Test and Deploy to GH Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Deploy to GitHub Pages
      if: success()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: . # Onde estão seus arquivos index.html, script.js, etc.
        branch: main # Branch de destino do deploy
